<?php
/**
 * @file
 * Support for dubious legal agreement during user registration.
 */
/**
 * Implements hook_form_alter().
 */
 function legalagree_form_alter(&$form, &$form_state, $form_id) {
 // check to see if the form is the user registration or user profile form
 // if not then return and don’t do anything
   if (!($form_id == 'user_register_form' || $form_id == 'user_profile_form' || $form_id == 'registration_form')) {
   return;
   }
 // add a new validate function to the user form to handle the legal agreement
   $form['#validate'][] = 'legalagree_user_form_validate';
 // add a field set to wrap the legal agreement
   $form['account']['legal_agreement'] = array(
     '#type' => 'fieldset',
     '#title' => t('Legal agreement')
   );
 // add the legal agreement radio buttons
   $form['account']['legal_agreement']['decision'] = array(
     '#type' => 'radios',
     '#description' => t('By registering at %site-name, you agree that
     at any time, we (or our team, %site-name) may contact you regarding any information filled by
     you and may cancel your account without informing you.',
     array('%site-name' => variable_get('site_name', 'drupal'))),
     '#default_value' => 0,
     '#options' => array(t('I disagree'), t('I agree'))
   );
}
/**
 * Form validation handler for the current password on the user_account_form().
 *
 * @see user_account_form()
 */
 function legalagree_user_form_validate($form, &$form_state) {
   global $user;
 // Did user agree?
   if ($form_state['input']['decision'] <> 1) {
     form_set_error('decision', t('You must agree to the Legal Agreement before registration
     can be completed.'));
   }
   else {
     watchdog('user', t('User %user agreed to legal terms', array('%user' => $user->uid)));
   }
 }